MangasExpress/Models/BaseEntity.cs
using MangasExpress.Interfaces;
using System;

namespace MangasExpress.Models
{
    public class BaseEntity : IEntity
    {
        public int Id { get; set; }
        public bool Status { get; set; } = true;
        public DateTime CreateAt { get; set; } = DateTime.Now;
        public DateTime? UpdateAt { get; set; }
    }
}

MangasExpress/Models/ErrorViewModel.cs
using System;

namespace MangasExpress.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MangasExpress/Models/Manga.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MangasExpress.Models
{
    public class Manga:BaseEntity
    {
        [Required(ErrorMessage = "El nombre es requerido")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El precio es requerido")]
        public double Precio { get; set; }
        [Required(ErrorMessage = "La descripcion es requerida")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El autor es requerido")]
        public string Autor { get; set; }
        [Required(ErrorMessage = "La marca es requerida")]
        public string Marca { get; set; }
        [Required(ErrorMessage = "La imagen es requerida")]
        public string Imagen { get; set; }
    }
}

MangasExpress/Models/MangaContext.cs
using Microsoft.EntityFrameworkCore;

namespace MangasExpress.Models
{
    public class MangaContext:DbContext
    {
        public MangaContext()
        {

        }
        public MangaContext(DbContextOptions<MangaContext> options):base(options)
        {

        }
        public DbSet<Manga> mangas { get; set; }
        public DbSet<Registrado> registrados { get; set; }
        public DbSet<Usuario> usuarios { get; set; }
    }
}

MangasExpress/Models/Registrado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MangasExpress.Models
{
    public class Registrado:BaseEntity
    {
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "El correo es requerido")]
        public string Correo { get; set; }
        [Required(ErrorMessage = "El nombre es requerido")]
        public string Nombre { get; set; }
    }
}

MangasExpress/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MangasExpress.Models
{
    public class Usuario:BaseEntity
    {
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "El correo no puede estar vacio")]
        [MaxLength(100,ErrorMessage ="El correo no puede superar los 100 caracteres")]
        public string Correo { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "La contraseña no puede estar vacia")]
        [MaxLength(50,ErrorMessage ="La contraseña no puede superar los 50 caracteres")]
        [MinLength(8,ErrorMessage ="La contraseña debe ser de al menos 8 caracteres")]
        public string Contrasenia { get; set; }
    }
}

MangasExpress/Controllers/HomeController.cs
using MangasExpress.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PagedList;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MangasExpress.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private MangaContext mangaContext;

        public HomeController(ILogger<HomeController> logger, MangaContext _context)
        {
            _logger = logger;
            mangaContext = _context;
        }


       [HttpGet]
        public IActionResult Index(string searchBy)
        {
            var mangas = string.IsNullOrEmpty(searchBy) ? mangaContext.mangas.Where(x => x.Status).ToList() : 
                mangaContext.mangas.Where(x => x.Status && x.Nombre.Contains(searchBy)).ToList();
            return View(mangas); 
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpGet]
        public IActionResult Details(int id)
        {

            var manga = mangaContext.mangas.FirstOrDefault(x => x.Id == id);
            return PartialView("_DetailsModelPartial", manga);
        }

    }
}

MangasExpress/Controllers/LoginController.cs
using MangasExpress.Models;
using MangasExpress.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace MangasExpress.Controllers
{
    public class LoginController : Controller
    {
        UsuarioRepository repository;
        public LoginController(UsuarioRepository _reporitory)
        {
            repository = _reporitory;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Usuario _usuario)
        {
            if (!ModelState.IsValid)
            {
                return View(_usuario);
            }
            var usuario = repository.loginUser(_usuario);
            if (usuario.Id > 0)
            {
                HttpContext.Session.SetString("Id", usuario.Id.ToString());
                return RedirectToAction("Index", "Home");
            }
           
            return View();
        }
        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Create(Usuario _usuario)
        {
            if (!ModelState.IsValid)
            {
                return View(_usuario);
            }
            var usuario = repository.createUser(_usuario);
            if (usuario.Id > 0)
            {
                HttpContext.Session.SetString("Id", usuario.Id.ToString());
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

MangasExpress/Controllers/MangasController.cs
using MangasExpress.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace MangasExpress.Controllers
{
    public class MangasController : Controller
    {
        private MangaContext mangaContext;

        public MangasController(MangaContext _context)
        {
            mangaContext = _context;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Manga manga)
        {
            mangaContext.mangas.Add(manga);
            mangaContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var manga = mangaContext.mangas.FirstOrDefault(x => x.Id == id);
            return View(manga);
        }

        public IActionResult Index()
        {
            var mangas = mangaContext.mangas.Where(x => x.Status).ToList();
            return View(mangas);
        }
        public IActionResult Update(int id)
        {
            var manga = mangaContext.mangas.FirstOrDefault(x => x.Id == id);
            return View(manga);
        }

        [HttpPost]
        public IActionResult Update(Manga manga)
        {
            var updateManga = mangaContext.mangas.Update(manga).Entity;
            mangaContext.SaveChanges();
            return View(updateManga);
        }
    }
}

MangasExpress/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}
@model List<Manga>

<head>

    <link rel="stylesheet" href="~/css/mangas.css">
</head>

<body>
    <div class="container-fluid text-center mb-4">
        <div class="customCarousel">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="https://img.assinaja.com/assets/tZ/050/img/369468_1140x366.jpg" alt="...">
                        <div class="carousel-caption d-none d-md-block">

                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="https://img.assinaja.com/assets/tZ/050/img/369472_1140x366.jpg" alt="...">
                        <div class="carousel-caption d-none d-md-block">

                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="https://img.assinaja.com/assets/tZ/050/img/369489_1140x366.jpg" alt="...">
                        <div class="carousel-caption d-none d-md-block">

                        </div>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>

    <div id="placeholderhere">
    </div>

    <h1 class="mangas">MANGAS</h1>
    <div class="single-product-area">
        <div class="container">
            <br />
            <div class="row">
                @foreach (var manga in Model)
                {
                    <div class="col-md-3 col-sm-6">
                        <div class="single-shop-product">
                            <div>
                                <img class="product-image" src="@manga.Imagen" alt="">
                            </div>
                            <h2><button class="btn nav-link" style="text-decoration:underline;" data-toggle="ajax-modal" data-target="#details" onclick="showModal(@manga.Id)">@manga.Nombre</button></h2>
                            <div class="product-carousel-price">
                                <ins>$ @manga.Precio</ins>
                            </div>
                            <br />
                            <div class="product-option-shop">
                                <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow">Agregar al carrito</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="visually-hidden">Previous</span>
                    </a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1 </a></li>
                <li class="page-item"><a class="page-link" href="#">2 </a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="visually-hidden">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</body>
@section scripts{
    <script type="text/javascript">
        function showModal(id) {
            var placeholderElement = $('#placeholderhere')
            var url = 'Home/Details' + '/' + id
            $.get(url).done(function (data) {
                placeholderElement.html(data)
                placeholderElement.find('.modal').modal('show')
            })
        }
        function destroyModal() {
            var placeholderElement = $('#placeholderhere')
            placeholderElement.find('.modal').modal('hide')
        }
    </script>
}

MangasExpress/Views/Home/_DetailsModelPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Manga
@{
}
<div id="details" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="details" class="modal-title">Detalles</h4>
                <button class="close btn " data-dismiss="modal" onclick="destroyModal()">
                    <span>x</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="single-shop-pronduct">
                    <div style="margin: auto; width: 50%; padding: 10px;">
                        <img class="product-image" src="@Model.Imagen" alt="">
                    </div>
                    <h2>@Model.Nombre</h2>
                    <p>@Model.Descripcion</p>
                    <div class="product-carousel-price">
                        <ins style="font-size:16px;">$ @Model.Precio</ins>
                    </div>
                    <br />
                </div>
            </div>

            <div class="modal-footer">
                <div class="product-option-shop">
                    <button type="button" data-save="modal" class="add_to_cart_button btn" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow">Agregar al carrito</button>
                    <button class="btn btn-danger" data-dismiss="modal" onclick="destroyModal()">
                        Cerrar
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        

    </script>
}

MangasExpress/Views/Login/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Usuario

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="~/css/login.css">
</head>
<body>
    <div class="logo"></div>
    <div class="login-block">
        <h1>Registrarse</h1>
        <form class="login" asp-action="Create" asp-controller="Login" method="post">
            @Html.LabelFor(model => model.Correo)
            <div class="form-group">
                @Html.EditorFor(model => model.Correo, "", new { @class = "username", placeholder = "Correo" })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Contrasenia)
            <div class="form-group">
                @Html.EditorFor(model => model.Contrasenia, "", new { @class = "password", placeholder = "Contraseña" })
                @Html.ValidationMessageFor(model => model.Contrasenia, "", new { @class = "text-danger" })
            </div>
            <button type="submit" class="btn btn-primary">Registrarse</button>
        </form>
    </div>
</body>
</html>

MangasExpress/Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Usuario
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="~/css/login.css">
</head>
<body>
    <div class="logo"></div>
    <div class="login-block">
        <h1>Login</h1>
        <form class="login" asp-action="Index" asp-controller="Login" method="post">
            @Html.LabelFor(model => model.Correo)
            <div class="form-group">
                @Html.EditorFor(model => model.Correo, "", new { @class = "username", placeholder = "Correo"  })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Contrasenia)
            <div class="form-group">
                @Html.EditorFor(model => model.Contrasenia, "", new { @class = "password", placeholder = "Contraseña" })
                @Html.ValidationMessageFor(model => model.Contrasenia, "", new { @class = "text-danger" })
            </div>
            <div>
                <a asp-route="Create" class="left-text">¿Olvidaste tu contraseña?</a>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>

            <div class="texto">
                <a asp-action="Create" class="center-text">Registrarse</a>
            </div>
        </form>
    </div>
    


        @*<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>*@
        <!--<div class="logo"></div>
        <div class="login-block">
            <h1>Login</h1>
            <input type="text" value="" placeholder="Username" id="username" />
            <input type="password" value="" placeholder="Password" id="password" />
            <button>Submit</button>
        </div>-->


</body>
</html>

MangasExpress/Views/Mangas/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Manga
@{
}


<!DOCTYPE html>
<html>
<head>
    <title>Crear manga</title>
    <link rel="stylesheet" href="~/css/mangas.css">
</head>
<body>

    <form method="post">

        <div class="col">
            <label asp-for="Nombre">Nombre del Manga</label>
            <input type="text" class="form-control" asp-for="Nombre" />
            <span class="text-danger" asp-validation-for="Nombre"></span>
        </div>


        <div class="col">
            <label asp-for="Precio">Precio</label>
            <input type="number" class="form-control" asp-for="Precio" />
            <span class="text-danger" asp-validation-for="Precio"></span>
        </div>


        <div class="col">
            <label asp-for="Descripcion">Descripción</label>
            <textarea class="form-control" asp-for="Descripcion"></textarea>
            <span class="text-danger" asp-validation-for="Descripcion"></span>
        </div>

        <div class="col">
            <label asp-for="Autor">Autor</label>
            <input type="text" class="form-control" asp-for="Autor" />
            <span class="text-danger" asp-validation-for="Autor"></span>
        </div>

        <div class="col">
            <label asp-for="Marca">Marca</label>
            <input type="text" class="form-control" asp-for="Marca" />
            <span class="text-danger" asp-validation-for="Marca"></span>
        </div>

        <div class="col">
            <label asp-for="Imagen">URL Imagen</label>
            <input type="text" class="form-control" asp-for="Imagen" />
            <span class="text-danger" asp-validation-for="Imagen"></span>
        </div><br />


        <button type="submit" value="Registrar" class="btn btn-primary">Registrar</button>|
        <button type="submit" value="" class="btn btn-danger" asp-action="Index">Cancelar</button>

    </form>


</body>
</html>

MangasExpress/Views/Mangas/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Manga
@{
}
<div id="placeholderhere"></div>
<div id="details" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="details" class="modal-title">Detalles</h4>
                <button class="close" data-dismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-md-3 col-sm-6">
                    <div class="single-shop-product">
                        <div>
                            <img class="product-image" src="@Model.Imagen" alt="">
                        </div>
                        <h2>@Model.Nombre</h2>
                        <div class="product-carousel-price">
                            <ins>$ @Model.Precio</ins>
                        </div>
                        <br />
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <div class="product-option-shop">
                    <button type="button" data-save="modal" class="add_to_cart_button btn" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow">Agregar al carrito</button>
                    <button class="btn btn-danger" data-dismiss="modal">
                        Close
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

MangasExpress/Views/Mangas/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Manga>

<!DOCTYPE html>
<html>
<head>
    <title>MangasExpress</title>
    <link rel="stylesheet" href="~/css/mangas.css">
</head>
<body>
    <h1>Todos los mangas</h1>
    <div class="single-product-area">
        <div class="container">
            <div class="row">
                @foreach (var manga in Model)
                {
                    <div class="col-md-3 col-sm-6">
                        <div class="single-shop-product">
                            <div>
                                <img class="product-image" src="@manga.Imagen" alt="">
                            </div>
                            <h2><a asp-controller="Mangas" asp-action="Details" asp-route-id="@manga.Id">@manga.Nombre</a></h2>
                            <div class="product-carousel-price">
                                <ins>$ @manga.Precio</ins>
                            </div>
                            <br />
                            <div class="product-option-shop">
                                <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow">Agregar al carrito</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>


    <div class="row">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="visually-hidden">Previous</span>
                    </a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1 </a></li>
                <li class="page-item"><a class="page-link" href="#">2 </a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="visually-hidden">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>

MangasExpress/Views/Mangas/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Manga


<!DOCTYPE html>
<html>
<head>
    <title>Crear manga</title>
    <link rel="stylesheet" href="~/css/mangas.css">
</head>
<body>

    <form method="post">

        <div class="col">
            <label asp-for="Nombre" for="nombre">Nombre del Manga</label>
            <input type="text" class="form-control" asp-for="Nombre" />
            <span class="text-danger" asp-validation-for="Nombre"></span>
        </div>


        <div class="col">
            <label asp-for="Precio" for="lugar">Precio</label>
            <input type="number" class="form-control" asp-for="Precio" />
            <span class="text-danger" asp-validation-for="Precio"></span>
        </div>


        <div class="col">
            <label asp-for="Descripcion" for="curp">Descripción</label>
            <textarea class="form-control" asp-for="Descripcion"></textarea>
            <span class="text-danger" asp-validation-for="Descripcion"></span>
        </div>

        <div class="col">
            <label asp-for="Autor" for="nss">Autor</label>
            <input type="text" class="form-control" asp-for="Autor" />
            <span class="text-danger" asp-validation-for="Autor"></span>
        </div>

        <div class="col">
            <label asp-for="Marca" for="nss">Marca</label>
            <input type="text" class="form-control" asp-for="Marca" />
            <span class="text-danger" asp-validation-for="Marca"></span>
        </div>

        <div class="col">
            <label asp-for="Imagen" for="rfc">URL Imagen</label>
            <input type="text" class="form-control" asp-for="Imagen" />
            <span class="text-danger" asp-validation-for="Imagen"></span>
        </div><br />


        <button type="submit" value="Registrar" class="btn btn-primary">Actualizar</button>|
        <button type="submit" value="" class="btn btn-danger" asp-page="/Menu">Cancelar</button>

    </form>


</body>
</html>

MangasExpress/Views/Shared/_Layout.cshtml
@{ 
    string searchBy = "";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MangasExpress</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg border-bottom box-shadow mb-4">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MangasExpress</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-right">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mangas" asp-action="Index">Productos</a>
                        </li>*@

                    </ul>
                </div>
                <form class="form-inline my-2 my-lg-0 d-flex">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" asp-for="@searchBy">
                    <button asp-action="Index" asp-controller="Home" asp-route-searchBy="@searchBy" class="btn btn-outline-primary my-2 my-sm-0" type="submit">Buscar</button>
                </form>
                <div class="nav-item float-right" style="float:right;">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fas fa-shopping-cart fa-2x"></i> Carrito</a>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h4>Atención al Cliente</h4>
                        <p>¿Necesitas ayuda?</p>
                        <p>Contáctanos</p>
                        <p>Tel: +52 999 251 9486</p>
                        <p>Tel: +52 999 645 9799</p>
                    </div>
                    <div class="col">
                        <h3>Redes sociales:</h3>
                        <i class="fab fa-facebook fa-2x"></i>
                        <i class="fab fa-twitter fa-2x"></i>
                    </div>
                    <div class=" col mb-2">
                        <h4>Suscríbete</h4>
                        <label for="exampleFormControlInput1" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="exampleFormControlInput2" placeholder="Nombre"><br>
                        <label for="exampleFormControlInput1" class="form-label">Escribe tu correo eletrónico</label>
                        <input type="email" class="form-control mb-3" id="exampleFormControlInput1" placeholder="name@example.com">
                        <button class="btn btn-success">Enviar</button>
                    </div>
                </div>

            </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.19/dist/sweetalert2.all.js" integrity="sha256-PZopa1wHe4oeNzNoNggQKQDmuHlq4DrjbQ16ZRJt/64=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>